### PR TITLE
Sendtag Confirm Flow

### PR DESCRIPTION
**Pull request by youngkidwarrior**
Work on Confirm Flow

Next PR will handle when confirm is successful

### CODE REVIEW

**Comment by youngkidwarrior** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/0xsend/sendapp/251?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#251** <a href="https://app.graphite.dev/github/pr/0xsend/sendapp/251?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#247** <a href="https://app.graphite.dev/github/pr/0xsend/sendapp/247?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @youngkidwarrior and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by 0xBigBoss — COMMENTED** [review]
stuck on "Checking your wallet address..."

Screenshot 2024-03-30 at 12 09 59

**Review by 0xBigBoss — COMMENTED** [review]
still no browser wallet option

Screenshot 2024-03-30 at 12 11 40

**Comment by youngkidwarrior** [comment]
@0xBigBoss What wallet are you using?
the extra wallets will show up if you aren't running any of the popular wallets listed.

See how frame shows up for me.

Screenshot 2024-03-30 at 1 04 41 PM

I can make it so "injected wallet" is always on the list

**Comment by youngkidwarrior** [comment]
Ah, I let copilot fill out the checking wallet check. My mistake 🤦‍♂️

**Review by 0xBigBoss — APPROVED** [review]
Didn't look at everything in depth, but looks pretty good.

**Comment by youngkidwarrior** [comment]
### Merge activity

* **Apr 2, 10:01 PM EDT**: @youngkidwarrior started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/0xsend/sendapp/251).

**Pull request merged**
