### PR TITLE
Fix Lint Warnings

### PR DESCRIPTION
**Pull request by youngkidwarrior**

### CODE REVIEW

**Comment by youngkidwarrior** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/0xsend/sendapp/85?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `main`
  * **PR #49** <a href="https://app.graphite.dev/github/pr/0xsend/sendapp/49?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #85** <a href="https://app.graphite.dev/github/pr/0xsend/sendapp/85?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/0xsend/sendapp/85?utm_source=stack-comment).

**Review by 0xBigBoss — DISMISSED** [review]
looks good to ignore that supabase folder didn't review everytthing else.

**Comment by youngkidwarrior** [comment]
### Merge activity

* **Jan 25, 6:32 PM**: @youngkidwarrior started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/0xsend/sendapp/85).

**Comment by youngkidwarrior** [comment]
@0xBigBoss I'm going to trim down this PR since it war made before the overwrite. https://github.com/0xsend/sendapp/pull/91
does a lot of what this fixes

**Pull request closed without merging**
