### PR TITLE
Implement redirect uri on sign in screen

### PR DESCRIPTION
**Pull request by youngkidwarrior**

### CODE REVIEW

**Comment by youngkidwarrior** [comment]
* **#514** <a href="https://app.graphite.dev/github/pr/0xsend/sendapp/514?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @youngkidwarrior and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by youngkidwarrior** [comment]
@0xBigBoss This looks like its going to be more difficult than just a query param. Navigating to `auth/onboarding` always triggers a re-navigate. My intuition is to use `localStorage` then clear it after. Any other ideas?

**Review by 0xBigBoss — APPROVED** [review]
lgtm, we should definitely add a test for this.

**Comment by youngkidwarrior** [comment]
### Merge activity

* **Jul 15, 10:07 PM EDT**: @youngkidwarrior started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/0xsend/sendapp/514).

**Pull request merged**
