### PR TITLE
Fix updating phone number

### PR DESCRIPTION
**Pull request by musidlo**

### CODE REVIEW

**Review by youngkidwarrior — COMMENTED** [review]
Looking good, but I noticed that on dev and main, the existing phone number is not set as default value.

Can we update the form here to show the currently registered phone number as default value?

**Review by youngkidwarrior — CHANGES_REQUESTED** [review]
Looking good, but I noticed that on dev and main, the existing phone number is not set as default value.

Can we update the form here to show the currently registered phone number as default value?

**Comment by youngkidwarrior** [comment]
I'll double check. Thought I loaded it up on local and it didn't have it. I'll let you know by tomorrow

**Comment by musidlo** [comment]
@youngkidwarrior did you had a moment to see it?

**Review by youngkidwarrior — APPROVED** [review]
lgtm

**Pull request merged**
