### PR TITLE
SignIn Screen Carousel with Images

### PR DESCRIPTION
**Pull request by youngkidwarrior**
Sign In Screen Carousel. Image changes every 7.5 seconds, for now, until styles catch up

### CODE REVIEW

**Comment by youngkidwarrior** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/0xsend/sendapp/87?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `main`
  * **PR #80** <a href="https://app.graphite.dev/github/pr/0xsend/sendapp/80?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #81** <a href="https://app.graphite.dev/github/pr/0xsend/sendapp/81?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #83** <a href="https://app.graphite.dev/github/pr/0xsend/sendapp/83?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
        * **PR #84** <a href="https://app.graphite.dev/github/pr/0xsend/sendapp/84?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
          * **PR #87** <a href="https://app.graphite.dev/github/pr/0xsend/sendapp/87?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/0xsend/sendapp/87?utm_source=stack-comment).

**Review by 0xBigBoss — COMMENTED** [review]
Let's host these images somewhere else. We do have this repo, https://github.com/0xsend/assets

e.g. https://0xsend.github.io/assets/send-token.jpg

**Review by 0xBigBoss — COMMENTED** [review]
Also let's optimize them, 200KB+ is too large or let's go back and use SVG icons instead.

**Comment by youngkidwarrior** [comment]
Yeah, just wanted to get them in the PR. Going to optimize in a future PR

**Comment by youngkidwarrior** [comment]
@0xBigBoss last approval needed :D

**Review by 0xBigBoss — APPROVED** [review]
sry missed this one @youngkidwarrior . next time make sure you re-request review, i'm less likely to miss it.

**Comment by youngkidwarrior** [comment]
@0xBigBoss can do. Sorry gotta make the habit to request reviews 😀

**Comment by youngkidwarrior** [comment]
### Merge activity

* **Feb 7, 3:08 AM EST**: @youngkidwarrior started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/0xsend/sendapp/87).

**Pull request merged**
