### PR TITLE
SendTag Pricing Tooltip

### PR DESCRIPTION
**Pull request by youngkidwarrior**
We really need to get this Radix color schema locked down. Color styles are getting pretty messy

### CODE REVIEW

**Review by 0xBigBoss — COMMENTED** [review]
Looks like we missed updating the tests.



https://github.com/0xsend/sendapp/blob/a42de207bcfacc5cf13c17930cee0f24cee40db2/packages/playwright/tests/account-sendtag-checkout.logged-in.spec.ts#L29-L35

Also, looks like we changed a lot of the labels on this page, we need to update the ones in the specs. The page fixture is here, https://github.com/0xsend/sendapp/blob/a42de207bcfacc5cf13c17930cee0f24cee40db2/packages/playwright/tests/fixtures/checkout/page.ts#L1.

**Comment by youngkidwarrior** [comment]
> Looks like we missed updating the tests.
> 
> 
> 
> https://github.com/0xsend/sendapp/blob/a42de207bcfacc5cf13c17930cee0f24cee40db2/packages/playwright/tests/account-sendtag-checkout.logged-in.spec.ts#L29-L35
> 
> Also, looks like we changed a lot of the labels on this page, we need to update the ones in the specs. The page fixture is here, https://github.com/0xsend/sendapp/blob/a42de207bcfacc5cf13c17930cee0f24cee40db2/packages/playwright/tests/fixtures/checkout/page.ts#L1.
> 
> 
> 
> 

Yeah I don't even know where to start with this one. Tons of conditional rendering based on screen size. Conditional rendering based on form input and database state.

Even more changes coming with the Confirm flow

I'm going to finalize all the changes on this page then attempt to tackle the tests.

**Comment by 0xBigBoss** [comment]
> > Looks like we missed updating the tests.
> > 
> > https://github.com/0xsend/sendapp/blob/a42de207bcfacc5cf13c17930cee0f24cee40db2/packages/playwright/tests/account-sendtag-checkout.logged-in.spec.ts#L29-L35
> > 
> > Also, looks like we changed a lot of the labels on this page, we need to update the ones in the specs. The page fixture is here, https://github.com/0xsend/sendapp/blob/a42de207bcfacc5cf13c17930cee0f24cee40db2/packages/playwright/tests/fixtures/checkout/page.ts#L1
> > .
> 
> Yeah I don't even know where to start with this one. Tons of conditional rendering based on screen size. Conditional rendering based on form input and database state.
> 
> Even more changes coming with the Confirm flow
> 
> I'm going to finalize all the changes on this page then attempt to tackle the tests.

Don't overthink it, most of the tests are very simple and only target our extra large screens. Most of them are failing cause we just removed/updated content so playwright can't locate the new elements.

**Review by 0xBigBoss — APPROVED** [review]

**Comment by youngkidwarrior** [comment]
### Merge activity

* **Mar 28, 11:28 PM EDT**: @youngkidwarrior started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/0xsend/sendapp/240).

**Pull request merged**
