### PR TITLE
splash page designs

### PR DESCRIPTION
**Pull request by stormcloud266**
* Updated home screen design
* Opens passkeys directly without having to navigate to the sign in page

Screenshot 2024-08-22 at 4 19 19 PM

Screenshot 2024-08-22 at 4 18 55 PM

### CODE REVIEW

**Comment by stormcloud266** [comment]
* **#679** <a href="https://app.graphite.dev/github/pr/0xsend/sendapp/679?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @stormcloud266 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by youngkidwarrior — CHANGES_REQUESTED** [review]
This is looking great shax. A couple changes

1. The buttons are not centered on small screens. Looks like they are left aligned. Would be cleaner to center them  
Screenshot 2024-08-22 at 4 43 44 PM

2. When I logout of the app it takes me to `auth/sign-in`.  It should go back to `/`. We should never see `auth/sign-in` it can be removed

https://github.com/user-attachments/assets/ee8d4fe5-61a4-4e76-9607-9d3a38ebedcc

**Comment by stormcloud266** [comment]
@youngkidwarrior buttons centered, sign-in page stuff in stacked PR

**Review by youngkidwarrior — APPROVED** [review]

**Comment by youngkidwarrior** [comment]
### Merge activity

* **Aug 24, 10:33 PM EDT**: @youngkidwarrior started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/0xsend/sendapp/679).

**Pull request merged**
