### PR TITLE
2024-04-23-Merge main into dev

### PR DESCRIPTION
**Pull request by youngkidwarrior**

### CODE REVIEW

**Comment by youngkidwarrior** [comment]
* **#346** <a href="https://app.graphite.dev/github/pr/0xsend/sendapp/346?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @youngkidwarrior and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by 0xBigBoss — COMMENTED** [review]
Somethings off with this merge. This would merge the "disable stuff" commit or the commit I added for main specifically to hide the pre-MVP stuff.

I think what I've been doing is creating a branch from dev, merging main into the new branch, and then opening a PR from that new branch to dev.

**Comment by youngkidwarrior** [comment]
I did that, but yeah something seemed off to me to have that code commented out. I'll try again

**Comment by 0xBigBoss** [comment]
> I did that, but yeah something seemed off to me to have that code commented out. I'll try again

You could also revert the "disable stuff" commit in this PR and that should clear it up.

https://github.com/0xsend/sendapp/commit/0a861f68c0c3e6feaaa973e57cd34b9ab9493a14

**Comment by 0xBigBoss** [comment]
Synced main and dev using this PR https://github.com/0xsend/sendapp/pull/348

**Pull request closed without merging**
