### PR TITLE
Use query params for search state

### PR DESCRIPTION
**Pull request by youngkidwarrior**

### CODE REVIEW

**Comment by youngkidwarrior** [comment]
* **#497** <a href="https://app.graphite.dev/github/pr/0xsend/sendapp/497?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @youngkidwarrior and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by 0xBigBoss — DISMISSED** [review]
test send/screen.test.tsx is failing. try this patch

```diff
diff --git a/packages/app/features/send/screen.test.tsx b/packages/app/features/send/screen.test.tsx
index 6eef17b3..ea37eb03 100644
--- a/packages/app/features/send/screen.test.tsx
+++ b/packages/app/features/send/screen.test.tsx
@@ -7,20 +7,27 @@ jest.mock('expo-router', () => ({
   usePathname: jest.fn().mockReturnValue('/send'),
 }))
 
-// const params = {}
-
 jest.mock('solito', () => {
   // console.log('mock solito')
   const mockCreateParam = jest.fn(() => {
     // console.log('createParam in')
     return {
       useParam: jest.fn(() => {
-        // console.log('useParam', name, opts)
-        return ['test', jest.fn()]
+        // console.log('useParam')
+        return [
+          'test',
+          () => {
+            // console.log('called!')
+          },
+        ]
       }),
       useParams: jest.fn(() => {
-        // console.log('useParams', name, opts)
-        return ['test', jest.fn()]
+        // console.log('useParams')
+        return {
+          setParams: () => {
+            // console.log('setParams')
+          },
+        }
       }),
     }
   })
@@ -63,7 +70,8 @@ import { useProfileLookup } from 'app/utils/useProfileLookup'
 describe('SendScreen', () => {
   it('should render with search when on /send and no recipient in params', async () => {
     jest.useFakeTimers()
-
+    // @ts-expect-error mock
+    usePathname.mockReturnValue('/send')
     const tree = render(
       <TamaguiProvider defaultTheme={'dark'} config={config}>
         <SendScreen />
```

**Comment by youngkidwarrior** [comment]
@0xBigBoss looks like that wasn't quite it. I'll take a look tomorrow

**Comment by youngkidwarrior** [comment]
### Merge activity

* **Jul 9, 4:19 PM EDT**: @youngkidwarrior started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/0xsend/sendapp/497).

**Pull request merged**
