### PR TITLE
Earn page subheader and time labels

### PR DESCRIPTION
**Pull request by youngkidwarrior**

### CODE REVIEW

**Comment by youngkidwarrior** [comment]
* **#224** <a href="https://app.graphite.dev/github/pr/0xsend/sendapp/224?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @youngkidwarrior and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by 0xBigBoss — APPROVED** [review]
flawless

**Comment by 0xBigBoss** [comment]
oh wait @youngkidwarrior dont forget to update the app test snapshots please.

**Comment by youngkidwarrior** [comment]
Yep haven't forgotten thanks

**Pull request merged**
